version: '2'
services:
  app:
    build: .
    volumes:
      - .:/code
    ports:
      - "3022:22"
      - "3000:8000"
  postgres:
    image: postgres:9.6.2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: django
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: app_db
    volumes:
      - .pgdata:/var/lib/postgresql/data/pgdata
